// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NyxCEngine.Database;

#nullable disable

namespace NyxCEngine.Migrations
{
    [DbContext(typeof(NyxDbContext))]
    [Migration("20260112050404_AdjustedBunchOfTablesV1")]
    partial class AdjustedBunchOfTablesV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NyxCEngine.Database.Tables.BackgroundMedia", b =>
                {
                    b.Property<string>("FilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("EndBufferSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(10.0);

                    b.Property<DateTime>("LastScannedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("FilePath");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_bg_customer");

                    b.ToTable("background_media", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerName");

                    b.ToTable("customer", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.CustomerBackground", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Cursor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FixedFilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("round_robin");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("customer_background", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.CustomerSchedule", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("BufferDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7);

                    b.Property<int>("JitterMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PostingTimes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("09:00,14:00,20:00");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Europe/London");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_schedule", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.Integration", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Picture")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Profile")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("IntegrationId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_integration_customer");

                    b.ToTable("integration", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.IntegrationOverride", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("ManualDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("IntegrationId");

                    b.ToTable("integration_override", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.IntegrationPolicy", b =>
                {
                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PostType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Platform", "PostType");

                    b.ToTable("integration_policy", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.PremadeVideoSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SegmentSeconds")
                        .HasColumnType("int");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("SplitAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetIntegrationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status", "LockedAtUtc");

                    b.ToTable("premade_video_series", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.ScheduledPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PostizPostId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PostizState")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReleaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("scheduled");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CustomerId", "ScheduledAtUtc")
                        .HasDatabaseName("idx_sched_customer_time");

                    b.HasIndex("IntegrationId", "ScheduledAtUtc")
                        .IsUnique();

                    b.ToTable("scheduled_post", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.ScriptItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentSha1")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("ReservedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("CustomerId", "UsedAtUtc")
                        .HasDatabaseName("idx_script_customer_unused");

                    b.ToTable("script_item", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.VideoAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AudioDurationSeconds")
                        .HasColumnType("float");

                    b.Property<string>("BackgroundFilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<double?>("BackgroundStartOffsetSeconds")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double?>("EndBufferSecondsUsed")
                        .HasColumnType("float");

                    b.Property<string>("Mp4Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ScriptFilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ScriptSha1")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("SeriesCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SeriesIndex")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("TargetIntegrationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TimestampsPath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WavPath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TargetIntegrationId");

                    b.HasIndex("CustomerId", "SourceType");

                    b.HasIndex("SeriesId", "SeriesIndex");

                    b.ToTable("video_asset", "dbo");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.BackgroundMedia", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.Customer", "Customer")
                        .WithMany("BackgroundMedia")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.CustomerBackground", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.Customer", "Customer")
                        .WithOne("Background")
                        .HasForeignKey("NyxCEngine.Database.Tables.CustomerBackground", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.CustomerSchedule", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.Customer", "Customer")
                        .WithOne("Schedule")
                        .HasForeignKey("NyxCEngine.Database.Tables.CustomerSchedule", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.Integration", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.Customer", "Customer")
                        .WithMany("Integrations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.IntegrationOverride", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.Integration", "Integration")
                        .WithOne("Override")
                        .HasForeignKey("NyxCEngine.Database.Tables.IntegrationOverride", "IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.PremadeVideoSeries", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.ScheduledPost", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.VideoAsset", "Asset")
                        .WithMany("ScheduledPosts")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NyxCEngine.Database.Tables.Customer", "Customer")
                        .WithMany("ScheduledPosts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NyxCEngine.Database.Tables.Integration", "Integration")
                        .WithMany("ScheduledPosts")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Customer");

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.ScriptItem", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.Customer", "Customer")
                        .WithMany("Scripts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.VideoAsset", b =>
                {
                    b.HasOne("NyxCEngine.Database.Tables.Customer", "Customer")
                        .WithMany("Assets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.Customer", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Background");

                    b.Navigation("BackgroundMedia");

                    b.Navigation("Integrations");

                    b.Navigation("Schedule");

                    b.Navigation("ScheduledPosts");

                    b.Navigation("Scripts");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.Integration", b =>
                {
                    b.Navigation("Override");

                    b.Navigation("ScheduledPosts");
                });

            modelBuilder.Entity("NyxCEngine.Database.Tables.VideoAsset", b =>
                {
                    b.Navigation("ScheduledPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
